server:
  port: 8081

spring:
  profiles:
    include: oauth

  thymeleaf:
    prefix: classpath:templates/
    check-template-location: true
    suffix: .html

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: true
    generate-ddl: true

  datasource:
    url: jdbc:postgresql://localhost:6343/single_sign_on_db
    username: daesoo
    password: daesoo123
    driver-class-name: org.postgresql.Driver

  security:
    oauth2:
      client:
        registration:
          google:

            scope: profile, email
            redirect-uri: http://localhost:8081/login/oauth2/code/google