version: "3"

services:
  db:
    image: postgres:11-alpine
    environment:
      TZ: Asia/Seoul
      POSTGRES_USER: daesoo
      POSTGRES_PASSWORD: daesoo123
      POSTGRES_DB: single_sign_on_db
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
    networks:
      - single-sign-on
    ports:
      - "6343:5432"
    restart: unless-stopped
    volumes:
      - ./pg_data:/var/lib/postgresql/data

networks:
  single-sign-on:
